/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.swagger.petstore.models;

import java.util.*;

public class ApiResponseBuilder {
    //the instance to build
    private ApiResponse apiResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ApiResponseBuilder() {
        apiResponse = new ApiResponse();
    }

    public ApiResponseBuilder code(Integer code) {
        apiResponse.setCode(code);
        return this;
    }

    public ApiResponseBuilder type(String type) {
        apiResponse.setType(type);
        return this;
    }

    public ApiResponseBuilder message(String message) {
        apiResponse.setMessage(message);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiResponse build() {
        return apiResponse;
    }
}