/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.swagger.petstore.models;

import java.util.*;

public class CategoryBuilder {
    //the instance to build
    private Category category;

    /**
     * Default constructor to initialize the instance
     */
    public CategoryBuilder() {
        category = new Category();
    }

    public CategoryBuilder id(Long id) {
        category.setId(id);
        return this;
    }

    public CategoryBuilder name(String name) {
        category.setName(name);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Category build() {
        return category;
    }
}