/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.swagger.petstore.models;

import java.util.*;
import org.joda.time.DateTime;

public class OrderBuilder {
    //the instance to build
    private Order order;

    /**
     * Default constructor to initialize the instance
     */
    public OrderBuilder() {
        order = new Order();
    }

    public OrderBuilder id(Long id) {
        order.setId(id);
        return this;
    }

    public OrderBuilder petId(Long petId) {
        order.setPetId(petId);
        return this;
    }

    public OrderBuilder quantity(Integer quantity) {
        order.setQuantity(quantity);
        return this;
    }

    public OrderBuilder shipDate(DateTime shipDate) {
        order.setShipDate(shipDate);
        return this;
    }

    /**
     * Order Status
     */
    public OrderBuilder status(StatusEnum status) {
        order.setStatus(status);
        return this;
    }

    public OrderBuilder complete(Boolean complete) {
        order.setComplete(complete);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Order build() {
        return order;
    }
}