/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.swagger.petstore.models;

import java.util.*;

public class PetBuilder {
    //the instance to build
    private Pet pet;

    /**
     * Default constructor to initialize the instance
     */
    public PetBuilder() {
        pet = new Pet();
    }

    public PetBuilder id(Long id) {
        pet.setId(id);
        return this;
    }

    public PetBuilder category(Category category) {
        pet.setCategory(category);
        return this;
    }

    public PetBuilder name(String name) {
        pet.setName(name);
        return this;
    }

    public PetBuilder photoUrls(List<String> photoUrls) {
        pet.setPhotoUrls(photoUrls);
        return this;
    }

    public PetBuilder tags(List<Tag> tags) {
        pet.setTags(tags);
        return this;
    }

    /**
     * pet status in the store
     */
    public PetBuilder status(Status1Enum status) {
        pet.setStatus(status);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Pet build() {
        return pet;
    }
}