/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.swagger.petstore.models;

import java.util.*;

public class TagBuilder {
    //the instance to build
    private Tag tag;

    /**
     * Default constructor to initialize the instance
     */
    public TagBuilder() {
        tag = new Tag();
    }

    public TagBuilder id(Long id) {
        tag.setId(id);
        return this;
    }

    public TagBuilder name(String name) {
        tag.setName(name);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Tag build() {
        return tag;
    }
}