/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.swagger.petstore.models;

import java.util.*;

public class UserBuilder {
    //the instance to build
    private User user;

    /**
     * Default constructor to initialize the instance
     */
    public UserBuilder() {
        user = new User();
    }

    public UserBuilder id(Long id) {
        user.setId(id);
        return this;
    }

    public UserBuilder username(String username) {
        user.setUsername(username);
        return this;
    }

    public UserBuilder firstName(String firstName) {
        user.setFirstName(firstName);
        return this;
    }

    public UserBuilder lastName(String lastName) {
        user.setLastName(lastName);
        return this;
    }

    public UserBuilder email(String email) {
        user.setEmail(email);
        return this;
    }

    public UserBuilder password(String password) {
        user.setPassword(password);
        return this;
    }

    public UserBuilder phone(String phone) {
        user.setPhone(phone);
        return this;
    }

    /**
     * User Status
     */
    public UserBuilder userStatus(Integer userStatus) {
        user.setUserStatus(userStatus);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public User build() {
        return user;
    }
}